### ISSUE TITLE
Video stuttering when adjusting audio offset past 0.8 seconds forward

### ISSUE THREAD

**Issue by gb160** [FernetMenta/kodi-agile#200]
hi I'm the guy from the Kodi forum who pointed out the issue with the video when the audio offset was adjusted,  i built your fixed version and I'm still getting almost the same issue on Mac OSX 10.12

It is marginally improved as the video no longer freezes completely , but the video starts to stutter quite badly at any forward offset above 0.8s.

https://pastebin.com/BWxYnuxc

**Comment by FernetMenta** [comment]
could you please build master branch of this repo and report back (I pushed another change)

**Comment by gb160** [comment]
@FernetMenta Yep, just built and its working perfectly now on OS X 10.12, many thanks for this!
