### ISSUE TITLE
ERROR: Invalid GUI Shader selected

### ISSUE THREAD

**Issue by some2** [FernetMenta/kodi-agile#201]
JFYI, compiled master (2608bb86791df311adbcd62e9a37a4375dc44b61) on Ubuntu Artful, kodi.log gets spammed with (while no gui is shown):

> ERROR: Invalid GUI Shader selected 1
> ERROR: Invalid GUI Shader selected 4
> ERROR: Invalid GUI Shader selected 3

Older versions (eg c25de694aa469e4b810848235d70500643c61cbf - Oct 4, 2017) are working.

**Comment by FernetMenta** [comment]
can you pastebin a full debug log?

**Comment by some2** [comment]
hXXp://paste.ubuntu.com/25734701/

**Comment by FernetMenta** [comment]
your installation seems to be corrupted. it lacks the shaders files, see log.
I just tried make install on Artful and it did install the shader files.

**Comment by some2** [comment]
Yep, sorry.. my failure.
